server:
  port: 9876
  servlet:
    context-path: /miapp

spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.1.20:3306/store
    username: matias
    password: mla
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
